version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: '/app'
    ports:
      - 3000:3000
    links:
      - mongodb
    command: npm start
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017